# This is a basic workflow to help you get stadrted with Actions

name: CI


on:
  
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Image
        run: |   
          docker build -t ${{secrets.USERNAME}}/portfolio:${{github.run_number}} . 
          docker build -t ${{secrets.USERNAME}}/portfolio
      - name: Push Image
        run: |
            docker login -u ${{secrets.USERNAME}} -p ${{secrets.PASSWORD}}
            docker push ${{secrets.USERNAME}}/portfolio:${{github.run_number}}
            docker push ${{secrets.USERNAME}}/portfolio

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
     - name: SSH to the server
       uses: appleboy/ssh-action@v1
       with:
         host:     ${{secrets.HOST}}
         username: ${{secrets.USERNAME_SSH}}
         key:      ${{secrets.KEY}}
         #port:     ${{secrets.PORT}}
         script: |
           docker rm -f resume
           docker run -d --name resume -p 8080:5001 ${{secrets.USERNAME}}/portfolio:${{github.run_number}}
         
           

       