name: Real time  ci/cd pipeline for portfolio app

on:
  
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
env: 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v4
  
      # - name: Unit Tests
      #  run: |
      #    python -m unittest discover -s app.py
      #     pytest
      - name: Build Image
        run: |   
          docker build -t ${{secrets.USERNAME}}/portfolio:${{github.run_number}} . 
          docker build -t ${{secrets.USERNAME}}/portfolio
      - name: Push Image
        run: |
            docker login -u ${{secrets.USERNAME}} -p ${{secrets.PASSWORD}}
            docker push ${{secrets.USERNAME}}/portfolio:${{github.run_number}}
            docker push ${{secrets.USERNAME}}/portfolio


         
           

       